load('ext://restart_process', 'docker_build_with_restart')

docker_build_with_restart(
	"ghcr.io/Beardev118/dyson-api", ".",
	dockerfile="Dockerfile.dev",
	entrypoint="cargo run",
	live_update=[
		sync('.', '/app/'),
	]
)

k8s_yaml('../infra/api.yaml')
k8s_resource(
  workload='dyson-api',
  port_forwards=8000
)
